### ISSUE TITLE
Carplay Support?

### ISSUE THREAD

**Issue by phillipunzen** [leinelissen/jellyfin-audio-player#250] opened 2024-08-26 10:18 UTC
Hello!
I use Jellyfin to sort my music collection. And your app is perfect for playing it from my phone.

Unfortunately, I don't currently have the option to control the app under Apple Carplay. Is an integration planned here?

I would be very happy about it because, as far as I know, there is no Carplay-capable Jellyfin app yet.

**Comment by leinelissen** [comment] 2024-08-26 14:47
Hey there @phillipunzen, great to hear you're enjoying the app. CarPlay is an often-requested feature. I would love to get it in, but it's not a priority right now. If you'd like to take a stab yourself, I can give you some directions.

**Comment by leinelissen** [comment] 2024-08-26 14:47
Duplicate of #44

**Closed by leinelissen** 2024-08-26 14:47 UTC
