### ISSUE TITLE
[Feature Request] Book/Audiobook support

### ISSUE THREAD

**Issue by HBIDamian** [leinelissen/jellyfin-audio-player#219] opened 2024-05-30 01:14 UTC
Currently the latest fdroid update doesn't support audiobooks that are under the "Books" library. 
Supporting it would be nice

**Comment by leinelissen** [comment] 2024-07-01 09:56
Hey, thanks for the suggestion! I would love to see this happen, but it's not a priority at this moment. I will be closing this issue as it is a duplicate of #79, where any support for audiobooks will be tracked.

**Closed by leinelissen** 2024-07-01 09:56 UTC
