### ISSUE TITLE
Audio sometimes replays from the start (opus/mka)

### ISSUE THREAD

**Issue by Behem07h** [leinelissen/jellyfin-audio-player#128] opened 2023-03-03 04:49 UTC
On server side these are .mka files encoded in opus audio codec. Other than the occasional restarting of the song, they play perfectly fine.
this seems to occur most often the first time a song is loaded since launching the app, and when it occurs the song continues to restart indefinitely until the song playing is changed manually

when this bug occurs the playback progress bar and timer continue counting without resetting, and when the total time played exceeds the original song, it begins counting in reverse and the playback bar similarly counts down from the left

![76ADD9E1-0F41-492D-B71E-786DC4486565](https://user-images.githubusercontent.com/44797371/222632410-5fe589b9-b408-4f3e-b953-f9a17f4fd725.png)

**Comment by Behem07h** [comment] 2023-03-03 04:52
my uninformed guess is that perhaps this is what happens when the file tries to play past what has been loaded in the scrubber, and rather than pausing the playback the audio simply restarts from the beginning

**Comment by leinelissen** [comment] 2023-03-06 10:07
Hey @Behem07h, thanks for pointing this out! As a matter of fact I can reproduce this with some AIFF-encoded files, where it'll start looping indefinitely. This is probably some form of miscommunication between the iOS Media Player and Jellyfin transcoding the file. I'll see if I can get to the bottom of this.

**Comment by Behem07h** [comment] 2023-03-27 22:54
Can confirm that it has to do with streaming the audio - I recently attempted to download the entire contents of a playlist for local playback and doing so eliminates this issue for the downloaded files

**Comment by leinelissen** [comment] 2023-03-28 08:36
Ah right. A potential fix in that case could be to fully buffer the file before playing it back. I still need to investigate, but this could be helpful.

**Comment by leinelissen** [comment] 2023-07-14 22:28
Duplicate of #97.

**Closed by leinelissen** 2023-07-14 22:28 UTC
Labels: bug
