### ISSUE TITLE
Album list flickering

### ISSUE THREAD

**Issue by regisfrias** [leinelissen/jellyfin-audio-player#116] opened 2022-12-09 05:18 UTC
When scrolling past some point in the all albums view the grid starts flickering (see video). I wonder if it's related to my library somehow, because it always happens at the same spot (letter C).

Sorry, I don't know if you can reproduce this with a different library, but I'll leave it documented here anyway.

https://user-images.githubusercontent.com/645531/206629129-fe9ad93f-1b20-427e-b0c8-5bb2ac696033.MOV

**Comment by leinelissen** [comment] 2022-12-09 09:24
Hey @regisfrias. Thanks for submitting this. This is unfortunately a known issue with no clear path to resolution yet. If you're interested in the details, we're tracking this in another issue. Closing as duplicate of #98

**Closed by leinelissen** 2022-12-09 09:24 UTC

**Comment by regisfrias** [comment] 2022-12-09 13:40
Thanks for your reply! And sorry for the duplicate. I did search before adding this here, but I guess I did it poorly.
