### ISSUE TITLE
Add support for playback reporting

### ISSUE THREAD

**Issue by the-r0cket06** [leinelissen/jellyfin-audio-player#14] opened 2020-09-07 19:23 UTC
Would you be willing to investigate implementing playback reporting?

**Comment by leinelissen** [comment] 2020-09-08 07:51
I'd consider it, but admittedly it would be pretty low on the priority list at this point. If you feel adventurous, I'd be happy to accept a pull request that implements the functionality. I can point you where to look for specific stuff if you need any help.

**Comment by attie** [comment] 2023-01-11 16:53
Is this a duplicate of #62? (there's more activity / interest over there)

**Comment by leinelissen** [comment] 2023-01-12 09:41
Yeah it would be good to track it in a single issue. Duplicate of #62

**Closed by leinelissen** 2023-01-12 09:41 UTC
Labels: enhancement
