### ISSUE TITLE
[Bug] WAV files don't play

### ISSUE THREAD

**Issue by mb0x88** [leinelissen/jellyfin-audio-player#177] opened 2023-08-12 03:22 UTC
Not getting any playback for wav files

Android 13(CalyxOS)

**Comment by leinelissen** [comment] 2023-08-13 18:38
This is a known issue and should be fixed in the upcoming update. I'm closing this since we're tracking this in another issue.

**Comment by leinelissen** [comment] 2023-08-13 18:39
Duplicate of #155

**Closed** 2023-08-13 18:39 UTC
