### ISSUE TITLE
Music doesn't get scrobbled

### ISSUE THREAD

**Issue by sseneca** [leinelissen/jellyfin-audio-player#114] opened 2022-12-04 13:05 UTC
When I listen to a track through the latest version of the app with the listenbrainz plugin enabled, tracks I listen to aren't scrobbled.

fwiw neither Gelli (https://github.com/dkanada/gelli/issues/143) or Finamp (https://github.com/jmshrv/finamp/issues/87) do this properly either

**Comment by leinelissen** [comment] 2022-12-05 09:39
Hi there! Thanks for the references. Support for scrobbling has been a long-requested feature. While I do find it interesting, I don't use it myself so I can't give any guarantees for implementations. Again, if you'd like any pointers on where to start out I am more than happy to provide them. Until then, I'm going to close this issue in favour of #62.

**Comment by leinelissen** [comment] 2022-12-05 09:40
Duplicate of #62

**Closed by leinelissen** 2022-12-05 09:40 UTC

**Comment by leinelissen** [comment] 2022-12-05 12:56
No worries ;)
