### ISSUE TITLE
[Feature Request] Support Downloads to SD card/other directories [Android]

### ISSUE THREAD

**Issue by snarkywolverine** [leinelissen/jellyfin-audio-player#246] opened 2024-08-15 01:27 UTC
Hello!

I would love to have the ability to download music from Jellyfin to my SD card - specifically, a directory I specify (rather than the application's default data folder).  This would dramatically help me transfer my Jellyfin collection to my watch (without having to get files off the Jellyfin server).

Is this something that's achievable?

Thanks!

**Comment by leinelissen** [comment] 2024-08-22 08:50
Hi there! Thanks for the suggestion. It would be a great addition and other people want this too. It is quite achievable, but requires a bit of work. I'm not looking at this currently, but if you want to speed things up I can give you some pointers where to start. I will close this issue so there is a single issue tracking the feature.

**Comment by leinelissen** [comment] 2024-08-22 08:50
Duplicate of #222.

**Closed by leinelissen** 2024-08-22 08:50 UTC
